### ISSUE TITLE
OpenAI API400

### ISSUE THREAD

**Issue by Fishbubu** [LorisYounger/VPet.Plugin.Demo#3]
您好，這邊想詢問如何刪除歷史聊天紀錄?
我已經手動將ChatGPT設定裡面的歷史紀錄手動刪除了，但還是會出現錯誤代碼400的問題。
OpenAI那邊也有儲值，也沒有甚麼需要開VPN的問題。

**Comment by huyyds01** [comment]
api key

**Comment by LorisYounger** [comment]
400 删下聊天记录,
以及已在之前的更新修复
