### ISSUE TITLE
可以增加语音模型吗

### ISSUE THREAD

**Issue by kikilloy** [LorisYounger/VPet.Plugin.Demo#6]
在B站看到几个基于Bert-Vits2训练的模型，说是支持TTS（不是指mod）但找不到地方添加，
这mod是否支持Bert-Vits2模型呢？
又如何添加呢？w

**Comment by LorisYounger** [comment]
不支持,只能自己写, 我之前在创意工坊看到了其他tts的实现, 你可以参考下那些
