### ISSUE TITLE
Feature: README补充关于install和build的步骤

### ISSUE THREAD

**Issue by LDY681** [LorisYounger/VPet.Plugin.Demo#7]
你好，感谢提供这个demo。
看完README和源代码后，依然有些疑问。
希望可以丰富下README，帮助我等.NET和C#小白更快上手。

目前有两个问题没太明白
1.install步骤有哪些？尝试了dotnet run但是会报错缺少using指令或引用。
2. 源码是如何打包成mod文件夹1100_DemoClock的？

谢谢

**Comment by huangdihd** [comment]
求同,不会编译

**Comment by LorisYounger** [comment]
需要visualstudio编译, 直接点生成就行. 不支持dotnet run
你可以直接把1100_DemoClock文件夹复制一份, 改改里面的info.lps文件内容, 删掉itemid和authorid, 替换下plugin文件夹成你自己的生层内容就行, lang是翻译, 很简单显而易见的, 不需要教程
关于制作mod的教程, 可以参考 https://steamcommunity.com/sharedfiles/filedetails/?id=3020642878
