### ISSUE TITLE
ChatGPT插件增加本地ollma等基于OpenAI-API形式的本地LLM调用

### ISSUE THREAD

**Issue by Peachesmoon** [LorisYounger/VPet.Plugin.Demo#9]
想使用本地的LLM，但是ChatGPT插件仅支持调用GPT-3.5-Turbo和GPT-4这两个OpenAI官方模型的调用，希望能够开放自定义模型名，谢谢！

**Comment by Peachesmoon** [comment]
所以，能做吗

**Comment by LorisYounger** [comment]
到时候会改成可输入手动修改的模式, 以及增加对API反馈异型的容忍度

**Comment by Peachesmoon** [comment]
谢谢，加油

**Comment by LorisYounger** [comment]
已完成

**Comment by Welsonpeaches** [comment]
感谢
已经用上了
![image](https://github.com/LorisYounger/VPet.Plugin.Demo/assets/91715867/76e9c91c-4d83-420b-97ff-d3cd601611c3)
